import { createHash } from "node:crypto";
import type { AgentMessage } from "@earendil-works/pi-agent-core";

export const RETENTION_DISCLOSURE =
  "Questions sent to this node are retained and visible to its owner.";
export const ANSWER_DISCLOSURE =
  "Generated by the owner's authorized AI proxy from owner-approved " +
  "publications; verify citations via get.";
export const ESTIMATE_SECONDS = 120;

const DEADLINE_MS = 180_000;
const RESULT_GRACE_MS = 60_000;
const CHECKPOINT_TTL_MS = 15 * 60_000;
const NO_REFUND_NOTE = "No automated refund exists yet; contact the node owner.";

export interface AnswerSettings {
  enabled: boolean;
  priceUsd: number;
  proxy: string;
}

export interface AnswerOutcome {
  status: "complete" | "refused" | "failed";
  answer?: string;
  cited?: string[];
  reason?: string;
}

export interface AnswerTelemetry {
  model: string;
  inputTokens: number;
  outputTokens: number;
  costUsd: number;
  toolCalls: number;
  durationMs: number;
}

export interface AnswerCheckpoint {
  messages: AgentMessage[];
  turns: number;
  viewed: string[];
}

interface ManifestRow {
  id: string;
  teaser: string;
  topic: string;
  kind: string;
  updated_at: string;
}

export interface AnswerJob {
  ticket_id: string;
  question: string;
  price_usd: number;
  status: "running" | "complete" | "refused" | "failed";
  answer: string;
  cited_publication_ids: string;
  reason: string;
  model: string;
  input_tokens: number;
  output_tokens: number;
  cost_usd: number;
  tool_calls: number;
  duration_ms: number;
  created_at: string;
  updated_at: string;
}

export async function manifest(env: Env): Promise<Record<string, unknown>> {
  const { results } = await env.LORE_DB.prepare(
    `SELECT public_id AS id, teaser, topic, kind,
            substr(updated_at, 1, 10) AS updated_at
     FROM publications WHERE teaser <> ''
     ORDER BY topic, updated_at DESC, public_id`
  ).all<ManifestRow>();
  const topics: Record<string, object[]> = {};
  for (const { id, teaser, topic, kind, updated_at } of results) {
    (topics[topic] ??= []).push({ id, teaser, kind, updated_at });
  }
  return { manifest_version: 1, publication_count: results.length, topics };
}

export function validPublicId(value: string): boolean {
  const body = value.slice(0, 16);
  return (
    /^[0-9a-f]{24}$/.test(value) &&
    value.slice(16) === createHash("sha256").update(body).digest("hex").slice(0, 8)
  );
}

export function newTicketId(): string {
  const bytes = new Uint8Array(8);
  crypto.getRandomValues(bytes);
  const body = [...bytes].map((byte) => byte.toString(16).padStart(2, "0")).join("");
  return body + createHash("sha256").update(body).digest("hex").slice(0, 8);
}

export async function readAnswerSettings(db: D1Database): Promise<AnswerSettings> {
  let rows: { key: string; value: string }[];
  try {
    ({ results: rows } = await db
      .prepare("SELECT key, value FROM node_settings")
      .all<{ key: string; value: string }>());
  } catch {
    return { enabled: false, priceUsd: 0, proxy: "" };
  }
  const values = Object.fromEntries(rows.map(({ key, value }) => [key, value]));
  const priceUsd = Number(values.answer_price_usd ?? 0);
  const proxy = values.proxy_preamble ?? "";
  const enabled =
    values.answer_enabled === "true" && proxy.trim() !== "" && Number.isFinite(priceUsd) && priceUsd > 0;
  return { enabled, priceUsd, proxy };
}

export async function ensureAnswerSchema(db: D1Database): Promise<void> {
  await db.batch([
    db.prepare(
      `CREATE TABLE IF NOT EXISTS answer_jobs (
      ticket_id TEXT PRIMARY KEY,
      question TEXT NOT NULL,
      price_usd REAL NOT NULL,
      status TEXT NOT NULL DEFAULT 'running'
        CHECK(status IN ('running','complete','refused','failed')),
      answer TEXT NOT NULL DEFAULT '',
      cited_publication_ids TEXT NOT NULL DEFAULT '[]',
      reason TEXT NOT NULL DEFAULT '',
      model TEXT NOT NULL DEFAULT '',
      input_tokens INTEGER NOT NULL DEFAULT 0,
      output_tokens INTEGER NOT NULL DEFAULT 0,
      cost_usd REAL NOT NULL DEFAULT 0,
      tool_calls INTEGER NOT NULL DEFAULT 0,
      duration_ms INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`
    ),
    db.prepare(
      `CREATE TABLE IF NOT EXISTS answer_checkpoints (
      ticket_id TEXT PRIMARY KEY,
      messages TEXT NOT NULL,
      turns INTEGER NOT NULL,
      viewed_publication_ids TEXT NOT NULL,
      expires_at TEXT NOT NULL
    )`
    ),
    db
      .prepare("DELETE FROM answer_checkpoints WHERE expires_at <= ?1")
      .bind(new Date().toISOString())
  ]);
}

export async function createTicket(env: Env, question: string, priceUsd: number): Promise<string> {
  const ticketId = newTicketId();
  const now = new Date().toISOString();
  await env.LORE_DB.prepare(
    `INSERT INTO answer_jobs(ticket_id,question,price_usd,status,created_at,updated_at)
     VALUES (?1,?2,?3,'running',?4,?4)`
  )
    .bind(ticketId, question, priceUsd, now)
    .run();
  return ticketId;
}

async function readJob(env: Env, ticketId: string): Promise<AnswerJob | null> {
  return await env.LORE_DB.prepare("SELECT * FROM answer_jobs WHERE ticket_id = ?1")
    .bind(ticketId)
    .first<AnswerJob>();
}

export async function runningJob(env: Env, ticketId: string): Promise<AnswerJob | null> {
  const job = await readJob(env, ticketId);
  return job?.status === "running" ? job : null;
}

export async function readCheckpoint(env: Env, ticketId: string): Promise<AnswerCheckpoint | null> {
  const row = await env.LORE_DB.prepare(
    "SELECT messages,turns,viewed_publication_ids FROM answer_checkpoints " +
      "WHERE ticket_id=?1 AND expires_at>?2"
  )
    .bind(ticketId, new Date().toISOString())
    .first<{ messages: string; turns: number; viewed_publication_ids: string }>();
  return row
    ? {
        messages: JSON.parse(row.messages) as AgentMessage[],
        turns: row.turns,
        viewed: JSON.parse(row.viewed_publication_ids) as string[]
      }
    : null;
}

export async function saveCheckpoint(
  env: Env,
  ticketId: string,
  checkpoint: AnswerCheckpoint
): Promise<void> {
  const expiresAt = new Date(Date.now() + CHECKPOINT_TTL_MS).toISOString();
  await env.LORE_DB.prepare(
    `INSERT INTO answer_checkpoints(ticket_id,messages,turns,viewed_publication_ids,expires_at)
     SELECT ?1,?2,?3,?4,?5 WHERE EXISTS (
       SELECT 1 FROM answer_jobs WHERE ticket_id=?1 AND status='running'
     ) ON CONFLICT(ticket_id) DO UPDATE SET messages=?2,turns=?3,
       viewed_publication_ids=?4,expires_at=?5`
  )
    .bind(
      ticketId,
      JSON.stringify(checkpoint.messages),
      checkpoint.turns,
      JSON.stringify(checkpoint.viewed),
      expiresAt
    )
    .run();
}

export async function finishJob(
  env: Env,
  ticketId: string,
  outcome: AnswerOutcome,
  telemetry: AnswerTelemetry
): Promise<boolean> {
  const [result] = await env.LORE_DB.batch([
    env.LORE_DB.prepare(
      `UPDATE answer_jobs SET status=?2, answer=?3, cited_publication_ids=?4, reason=?5,
       model=?6, input_tokens=?7, output_tokens=?8, cost_usd=?9, tool_calls=?10,
       duration_ms=?11, updated_at=?12
     WHERE ticket_id=?1 AND status='running'`
    ).bind(
        ticketId,
        outcome.status,
        outcome.answer ?? "",
        JSON.stringify(outcome.cited ?? []),
        outcome.reason ?? "",
        telemetry.model,
        telemetry.inputTokens,
        telemetry.outputTokens,
        telemetry.costUsd,
        telemetry.toolCalls,
        telemetry.durationMs,
        new Date().toISOString()
      ),
    env.LORE_DB.prepare("DELETE FROM answer_checkpoints WHERE ticket_id=?1").bind(ticketId)
  ]);
  return result.meta.changes === 1;
}

async function hasLiveCheckpoint(env: Env, ticketId: string): Promise<boolean> {
  const row = await env.LORE_DB.prepare(
    "SELECT 1 FROM answer_checkpoints WHERE ticket_id=?1 AND expires_at>?2"
  )
    .bind(ticketId, new Date().toISOString())
    .first();
  return row !== null;
}

export async function ticketResult(env: Env, ticketId: string): Promise<Record<string, unknown>> {
  let job = await readJob(env, ticketId);
  if (!job) return { error: `ticket not found: ${ticketId}` };
  if (
    job.status === "running" &&
    Date.now() - Date.parse(job.created_at) > DEADLINE_MS + RESULT_GRACE_MS &&
    !(await hasLiveCheckpoint(env, ticketId))
  ) {
    await env.LORE_DB.batch([
      env.LORE_DB.prepare(
        "UPDATE answer_jobs SET status='failed', reason=?2, updated_at=?3 " +
          "WHERE ticket_id=?1 AND status='running'"
      ).bind(ticketId, "the agent did not finish in time", new Date().toISOString()),
      env.LORE_DB.prepare("DELETE FROM answer_checkpoints WHERE ticket_id=?1").bind(ticketId)
    ]);
    job = (await readJob(env, ticketId)) ?? job;
  }
  if (job.status === "running") return { status: "running", estimate_seconds: ESTIMATE_SECONDS };
  if (job.status === "complete") {
    return {
      status: "complete",
      answer: job.answer,
      cited_publication_ids: JSON.parse(job.cited_publication_ids) as string[],
      disclosure: ANSWER_DISCLOSURE
    };
  }
  return {
    status: job.status,
    reason: job.reason || (job.status === "refused" ? "no coverage" : "agent error"),
    note: NO_REFUND_NOTE
  };
}
