/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: b8b75818f16ba8bc6b6aa24add51fbc4)
interface __BaseEnv_Env {
	STRIPE_API: "https://api.stripe.com";
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	ACCOUNT_TOKEN_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
