/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 40bf82f7b198314e3f78b694f51a24e0)
interface __BaseEnv_Env {
	STRIPE_API: "https://api.stripe.com";
	STRIPE_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
