/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 81441d6e19a5c3cb3b53c5ba82fb2751)
interface __BaseEnv_Env {
	LORE_DB: D1Database;
	LORE_FACILITATOR_URL: "https://x402.org/facilitator";
	LORE_WALLET: string;
	LorePaidMCP: DurableObjectNamespace<import("./src/index").LorePaidMCP>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "LorePaidMCP";
	}
	interface QaEnv {
		LORE_DB: D1Database;
		LORE_FACILITATOR_URL: "https://x402.org/facilitator";
		LORE_WALLET: string;
		LorePaidMCP: DurableObjectNamespace<import("./src/index").LorePaidMCP>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LORE_FACILITATOR_URL" | "LORE_WALLET">> {}
}
