/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 2e85dba3f97677d38e71509e11b61522)
interface __BaseEnv_Env {
	FEEDBACK_RATE_LIMIT: RateLimit;
	GLOBAL_RATE_LIMIT: RateLimit;
	LORE_GITHUB_API: "https://api.github.com";
	LORE_FEEDBACK_GITHUB_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
