/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 3335dc72c075f3d592bb5522254e55b0)
interface __BaseEnv_Env {
	FEEDBACK_RATE_LIMIT: RateLimit;
	GLOBAL_RATE_LIMIT: RateLimit;
	LORE_GITHUB_API: "https://api.github.com";
	LORE_FEEDBACK_GITHUB_TOKEN: string;
	FEEDBACK_QUOTA: DurableObjectNamespace<import("./src/index").FeedbackQuota>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "FeedbackQuota";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
