/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: b56ffc6531b4ad392b9a338227819aad)
interface __BaseEnv_Env {
	FEEDBACK_RATE_LIMIT: RateLimit;
	GLOBAL_RATE_LIMIT: RateLimit;
	EVENTS_RATE_LIMIT: RateLimit;
	LORE_GITHUB_API: "https://api.github.com";
	LORE_FEEDBACK_GITHUB_TOKEN: string;
	POSTHOG_HOST: "https://us.i.posthog.com";
	POSTHOG_KEY?: string;
	FEEDBACK_QUOTA: DurableObjectNamespace<import("./src/index").FeedbackQuota>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "FeedbackQuota";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
