/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 1da203c1b8a5c86a70f4334d8165f8c8)
interface __BaseEnv_Env {
	LorePaidMCP: DurableObjectNamespace<import("./src/index").LorePaidMCP>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "LorePaidMCP";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
